### ISSUE TITLE
Charka

### ISSUE THREAD

**Issue by mathiasrw** [travis-ci/travis-next#2]
_This might not be the right place to ask. If not please let me know where to post a feature request_

Any plans to support tests of javascript with [Chakra from Microsoft](https://github.com/nodejs/node-chakracore/releases)?

It could be done like the IOjs where `.travis.yml` has 

``` yaml
language: node_js
node_js: 
  - "chakra"
  - "iojs"
```

Or with a new options for `language`:

``` yaml
language: chakra
chakra: 
  - "6"
```
